cabinetabinet:
    resource: "@CabinetabinetBundle/Resources/config/routing.yml"
    prefix:   /doc

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"